=== grehaj/ghnstat/sample/stat.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1691242336.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"interface_ip",
		"interface_name",
		"period_length",
		"period_start",
		"stat",
		"stat_count"
	],
	"properties": {
		"interface_ip": {
			"$id": "#root/interface_ip", 
			"title": "Interface_ip", 
			"type": "string",
			"default": "",
			"examples": [
				"1.1.1.1"
			],
			"pattern": "^.*$"
		},
		"interface_name": {
			"$id": "#root/interface_name", 
			"title": "Interface_name", 
			"type": "string",
			"default": "",
			"examples": [
				"wlp2s0"
			],
			"pattern": "^.*$"
		},
		"period_length": {
			"$id": "#root/period_length", 
			"title": "Period_length", 
			"type": "integer",
			"examples": [
				1
			],
			"default": 0
		},
		"period_start": {
			"$id": "#root/period_start", 
			"title": "Period_start", 
			"type": "string",
			"default": "",
			"examples": [
				"Sat Jul 29 12:55:48 2023"
			],
			"pattern": "^.*$"
		},
		"stat": {
			"$id": "#root/stat", 
			"title": "Stat", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/stat/items", 
				"title": "Items", 
				"type": "object",
				"required": [
					"ports",
					"time",
					"time_count"
				],
				"properties": {
					"ports": {
						"$id": "#root/stat/items/ports", 
						"title": "Ports", 
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/stat/items/ports/items", 
							"title": "Items", 
							"type": "object",
							"required": [
								"details",
								"port",
								"port_count"
							],
							"properties": {
								"details": {
									"$id": "#root/stat/items/ports/items/details", 
									"title": "Details", 
									"type": "array",
									"default": [],
									"items":{
										"$id": "#root/stat/items/ports/items/details/items", 
										"title": "Items", 
										"type": "object",
										"required": [
											"src",
											"src_count"
										],
										"properties": {
											"src": {
												"$id": "#root/stat/items/ports/items/details/items/src", 
												"title": "Src", 
												"type": "object",
												"required": [
													"ip",
													"port"
												],
												"properties": {
													"ip": {
														"$id": "#root/stat/items/ports/items/details/items/src/ip", 
														"title": "Ip", 
														"type": "string",
														"default": "",
														"examples": [
															"1.1.1.1"
														],
														"pattern": "^.*$"
													},
													"port": {
														"$id": "#root/stat/items/ports/items/details/items/src/port", 
														"title": "Port", 
														"type": "integer",
														"examples": [
															443
														],
														"default": 0
													}
												}
											}
,
											"src_count": {
												"$id": "#root/stat/items/ports/items/details/items/src_count", 
												"title": "Src_count", 
												"type": "integer",
												"examples": [
													6
												],
												"default": 0
											}
										}
									}

								},
								"port": {
									"$id": "#root/stat/items/ports/items/port", 
									"title": "Port", 
									"type": "integer",
									"examples": [
										37343
									],
									"default": 0
								},
								"port_count": {
									"$id": "#root/stat/items/ports/items/port_count", 
									"title": "Port_count", 
									"type": "integer",
									"examples": [
										6
									],
									"default": 0
								}
							}
						}

					},
					"time": {
						"$id": "#root/stat/items/time", 
						"title": "Time", 
						"type": "string",
						"default": "",
						"examples": [
							"Sat Jul 29 12:55:48 2023"
						],
						"pattern": "^.*$"
					},
					"time_count": {
						"$id": "#root/stat/items/time_count", 
						"title": "Time_count", 
						"type": "integer",
						"examples": [
							6
						],
						"default": 0
					}
				}
			}

		},
		"stat_count": {
			"$id": "#root/stat_count", 
			"title": "Stat_count", 
			"type": "integer",
			"examples": [
				6
			],
			"default": 0
		}
	}
}

=== grehaj/ghnstat/sample/stat_2.json
{
  "interface_ip": "1.1.1.1",
  "interface_name": "wlp2s0",
  "period_length": 10,
  "period_start": "Sat Jul 29 12:55:48 2023",
  "stat": [
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 6
            }
          ],
          "port": 37343,
          "port_count": 6
        }
      ],
      "time": "Sat Jul 29 12:55:48 2023",
      "time_count": 6
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 33793,
          "port_count": 1
        },
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 3
            }
          ],
          "port": 35588,
          "port_count": 3
        }
      ],
      "time": "Sat Jul 29 12:55:49 2023",
      "time_count": 4
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 3
            }
          ],
          "port": 35588,
          "port_count": 3
        },
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 51534,
          "port_count": 1
        }
      ],
      "time": "Sat Jul 29 12:55:50 2023",
      "time_count": 4
    },
    {
      "ports": [],
      "time": "Sat Jul 29 12:55:51 2023",
      "time_count": 0
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 3
            }
          ],
          "port": 35588,
          "port_count": 3
        },
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 50280,
          "port_count": 1
        }
      ],
      "time": "Sat Jul 29 12:55:52 2023",
      "time_count": 4
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 3
            }
          ],
          "port": 35588,
          "port_count": 3
        },
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 40456,
          "port_count": 1
        }
      ],
      "time": "Sat Jul 29 12:55:53 2023",
      "time_count": 4
    },
    {
      "ports": [],
      "time": "Sat Jul 29 12:55:54 2023",
      "time_count": 0
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 443
              },
              "src_count": 3
            }
          ],
          "port": 35588,
          "port_count": 3
        },
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 46970,
          "port_count": 1
        }
      ],
      "time": "Sat Jul 29 12:55:55 2023",
      "time_count": 4
    },
    {
      "ports": [],
      "time": "Sat Jul 29 12:55:56 2023",
      "time_count": 0
    },
    {
      "ports": [
        {
          "details": [
            {
              "src": {
                "ip": "1.1.1.1",
                "port": 53
              },
              "src_count": 1
            }
          ],
          "port": 33185,
          "port_count": 1
        }
      ],
      "time": "Sat Jul 29 12:55:57 2023",
      "time_count": 1
    }
  ],
  "stat_count": 27
}
